; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = d1_mini-release
src_dir = back/src
lib_dir = back/lib
include_dir = back/include
test_dir = back/test
data_dir = back/data

[base_d1_mini]
platform = espressif8266
framework = arduino
board = d1_mini
board_build.filesystem = littlefs
board_build.f_cpu = 80000000L
board_build.flash_mode = dio
board_build.flash_size = 4MB

[env]
monitor_speed = 57600
monitor_parity = O
extra_scripts = 
	pre:load_env.py
	back/filter.py

[libs]
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
	ESP32Async/ESPAsyncTCP@2.0.0
	ESP32Async/ESPAsyncWebServer@^3.10.0
	arduino-libraries/NTPClient@^3.2.1
	crankyoldgit/IRremoteESP8266@^2.9.0
	knolleary/PubSubClient@^2.8

[profile-release]
build_type = release
monitor_filters = hexlify
build_flags = 
	-std=gnu++17
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-DNDEBUG
	-DRELEASE_BUILD
	-DDEBUG_ESP_CORE_LEVEL=0
build_src_flags = 
	-D COMPILE_UNIX_TIME=$UNIX_TIME
	-Wall
	-Wextra
	-Wunused
	-Wpedantic
	-Wconversion
	-Wshadow

[profile-debug]
build_type = debug
monitor_filters = esp8266_exception_decoder
build_flags = 
	-Og
	-g3
	-DDEBUG_BUILD
	-DDEBUG_ESP_HEAP
	-DDEBUG_ESP_PORT=Serial
	-DDEBUG_ESP_HTTP_SERVER

[env:d1_mini-release]
extends = base_d1_mini, libs, profile-release

[env:d1_mini-debug]
extends = base_d1_mini, libs, profile-debug
